README.md
install-php-extensions

Add --cleanup option

---

README.md
install-php-extensions

The `--cleanup` option also uses an `apt autoremove` command.

---

install-php-extensions

See https://github.com/docker-library/php/issues/891#issuecomment-531023107
Credits to @tianon

Get imap ready for PHP 7.4

---

install-php-extensions

If the igbinary module is installed, let's enable its support for redis

Enable igbinary support for redis

---

install-php-extensions

If the igbinary/msgpack modules are installed, let's enable their support for memcached

Enable igbinary/msgpack support for memcached

---

install-php-extensions
scripts/travisci-test-new-extensions

Fix GD and ZIP configuration with PHP 7.4.0

---

.travis.yml
README.md
data/supported-extensions
install-php-extensions
scripts/travisci-test-extensions

Add Alpine support

---

install-php-extensions

[Debian 9] libssh-dev conflicts with libssl-dev, use libssl1.0-dev instead

---

install-php-extensions

Fix GD on Jessie

---

install-php-extensions

Available since redis extension version 5.1.0

Enable zstd support for redis

---

.travis.yml
install-php-extensions
scripts/invoke-shfmt
scripts/test-restore-apt

Restore previously installed APT packages

---

install-php-extensions

This should speed up tests a lot

Don't upgrade Debian packages

---

install-php-extensions

So that we don't have to call `getDistro` and `getDistroVersion` many times

Define DISTRO and DISTRO_VERSION

---

install-php-extensions

Enable parallel compilation for many pecl extensions

---

install-php-extensions

Don't assume than nproc is available

---

.github/workflows/test-extensions.yml
install-php-extensions

Fix building ldap for 32-bit OSs

---

install-php-extensions

Xdebug 3.0.0 has just been released.

Updates for new xdebug version

---

install-php-extensions

https://bugs.php.net/bug.php?id=78560 has been resolved

Avoid workaround for PECL issue with ssh2

---

.github/workflows/test-extensions.yml
README.md
install-php-extensions
scripts/test-installversion

Everything should be ready. I only have to write some tests.
Fix #130

Let users install a specific PHP module version

---

install-php-extensions
scripts/tests/imagick

Let imagick understand SVG

---

install-php-extensions

Fix installation of zookeeper in Alpine linux

---

install-php-extensions

Use latest Oracle InstantClient on Alpine Linux too

---

install-php-extensions

Avoid using hard-coded x86_64-linux-gnu target triplet

---

install-php-extensions

I'm starting to really dislike pickle... :(

Install pickle from master when required

---

install-php-extensions
scripts/tests/dba

Add support for DB4 to DBA

---

install-php-extensions

See https://mlocati.github.io/pecl-info/#rdkafka

Fix installing rdkafka in PHP 5.6

---

install-php-extensions

...lest save some space in the final Docker image...

Instruct composer to not use cache when building pickle

---

.github/workflows/readme-release.yml
install-php-extensions
scripts/ci-test-extensions
scripts/test-installcomposer
scripts/test-installversion
scripts/test-restore-apt

Let's add a version to the script, so that we can avoid issues like https://github.com/mlocati/docker-php-extension-installer/issues/242#issuecomment-755247367

Add script version

---

install-php-extensions

Zstandard parameterized url

---

data/special-requirements
install-php-extensions
scripts/tests/pdo_sqlsrv
scripts/tests/sqlsrv

Install Microsoft ODBC Drivers when using sqlsrv / pdo_sqlsrv

---

.github/workflows/test-extensions.yml
README.md
install-php-extensions
scripts/test-installversion

Support installing generic versions of extensions

---

install-php-extensions

See https://github.com/swoole/swoole-src/issues/3934 and https://github.com/swoole/swoole-src/commit/187efa3b6a65083019b25b33767774df9e258b9f

Enable SSL for swoole whenever possible

---

install-php-extensions

Not a huge typo, anyway... :wink:

Fix typo in script version warning message

---

install-php-extensions

Check installer signature when installing composer

---

install-php-extensions

Remove no more needed patches for imagick with PHP 8+

---

MAINTAINERS.md
install-php-extensions

Ant is not used anymore: https://stackoverflow.com/questions/64916994/build-xml-does-not-exist-when-install-zookeeper-client-c#comment116094374_65657279

Use maven instead of ant when building zookeeper

---

.github/workflows/test-extensions.yml
install-php-extensions
scripts/ci-markused-alpine
scripts/ci-markused-buster

Mark pre-installed required APT/APK packages as used

---

install-php-extensions

Use last stable mongodb version on PHP 7.0+

---

install-php-extensions

Cosmetic fix but clarify english

Typo error in function name

---

README.md

Following your comment https://github.com/mlocati/docker-php-extension-installer/issues/379#issuecomment-874135850

How to handle pre-release versions

---

install-php-extensions
scripts/ci-markused-alpine

Fix APK dependencies after installyng APK packages

---

install-php-extensions

Install unzip when installing composer

---

README.md
install-php-extensions
scripts/lint
scripts/lint.bat

 Let users keep the system packages cache 

---

data/special-requirements
install-php-extensions

Compile libenchant1 from source for PHP 5/7 when not provided by the system

---

install-php-extensions
scripts/tests/ioncube_loader

 Fix installing ionCube in multiarch, fix installing SourceGuardian for 32-bit PHP

---

README.md
install-php-extensions
scripts/tests/gd

Enable AVIF for GD on PHP 8.1

---

install-php-extensions

Fix installing tiny on Alpine 3.15

---

install-php-extensions

Fix installing lzf of PHP 7.1-

---

install-php-extensions

Test: apcu, igbinary, igbinary+apcu

Support serialize for apcu

---

data/special-requirements
install-php-extensions

sqlsrv and pdo_sqlsrv; use Microsoft ODBC 18 when available, support Debian Bullseye

---

data/special-requirements
install-php-extensions

Install msodbcsql18 alone on Debian 11

---

install-php-extensions

Strip symbols from compiled extensions

---

install-php-extensions

Check that compiled bundled PHP modules work

---

install-php-extensions

Abort if installing PHP extensions introduces new PHP startup errors

---

install-php-extensions

Avoid apk upgrade

---

install-php-extensions

Fix detecting the so module for the apcu_bc PHP extension

---

.github/workflows/test-extensions.yml
README.md
install-php-extensions

Ability to install extensions from source code/specific commits

---

install-php-extensions

Fix INI ordering issue with openswoole and sockets on Alpine (#554)

---

install-php-extensions

See https://github.com/protocolbuffers/protobuf/issues/9724

Fix installing protobuf on PHP 7/8

---

install-php-extensions

Installing protobuf via pecl/pickle as been fixed by https://github.com/protocolbuffers/protobuf/pull/9727

Install latest version of protobuf

---

install-php-extensions

The issue has already been fixed by
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/php/excimer/+/aed4ff82438e05e8c744ec5a7a1aa892aa9ac6f7
but we need to wait for a new version

Fix installing excimer on PHP 7.1

---

install-php-extensions

The fix has been published so we can revert https://github.com/mlocati/docker-php-extension-installer/pull/570

Use latest excim version on PHP 7.1 too

---

install-php-extensions

Fix installing event

---

install-php-extensions
scripts/tests/intl

Fix intl on Alpine 3.16 by installing icu-data-full

---

README.md
install-php-extensions

Let users install a smaller but English-only ICU lib

---

README.md
install-php-extensions
scripts/ci-test-extensions
scripts/tests/pspell

Support installing custom languages for pspell

---

install-php-extensions

Fix installing xdebug 3.2 on Alpine Linux

---

install-php-extensions

See also https://github.com/mlocati/docker-php-extension-installer/tree/assets

Use a more stable source for libxdiff

---

install-php-extensions

See https://github.com/protocolbuffers/protobuf/issues/10619

Hardcode last protobuf version

---

install-php-extensions

Fix xdebug with PHP 7.2/7.3/7.4, xdebug 3.2 GA

---

README.md

I added a part in the readme that indicates how to use the script without having to store it, chmod it and delete it

Added direct execution from curl

---

MAINTAINERS.md
install-php-extensions

There's no stable/beta version published on PECL

Install alpha versions of the ION extension

---

install-php-extensions

Use pickle only if pecl is not installed

---

.github/workflows/monitor-php8.2.yml
.github/workflows/test-extensions.yml
.github/workflows/test-recent-extensions.yml
LICENSE
install-php-extensions

Add support for Alpine 3.17

---

install-php-extensions

Update openswoole configure options to version 22.0.0

---

install-php-extensions

fix this issue. !grep => ! grep

install-php-extensions: 3856: !grep: not found

---

install-php-extensions

Fix installing sqlsrv and pdo_sqlsrv

---

.github/workflows/test-extensions.yml
install-php-extensions
scripts/test-icu-data-en-upgradable

Tell apk that icu-data-en can be upgraded to icu-data-full

---

install-php-extensions

Fix installing redis on PHP 7.0/7.1, add support for msgpack/lz4 to redis on PHP 7.2+

---

data/special-requirements
install-php-extensions

Thanks to @AKorezin for inspecting what we need

Add support for memcached on Debian Bookworm

---

install-php-extensions

Install the latest version of rust, cargo, and datadog_trace

---

install-php-extensions

Fix installing pdo_sqlsrv/sqlsrv on Debian Bookworm

---

.github/workflows/test-extensions.yml
README.md
install-php-extensions
scripts/test-installversion

Allow specifying stability when wanting a compatible PECL version

---

scripts/ci-test-extensions

See https://github.com/docker-library/php/pull/1464

PHP 8.3 is generally available

---

install-php-extensions
scripts/tests/swoole

Fix segmentation fault of swoole on PHP 8.3

---

install-php-extensions

Fix installing libssl on Alpine 3.19

---

data/special-requirements
install-php-extensions

Add support for imagick on Alpine 3.19

---

install-php-extensions

Install swoole 5.0 in 32-bit systems

---

install-php-extensions

Fix installing datadog_trace when specifying the version

---

install-php-extensions

Fix installing tideways on Alpine Linux

---

README.md
install-php-extensions

Delete newrelic install logs

---

install-php-extensions

Fix installing http on ZTS versions

---

scripts/update-readme

Reverse order of PHP version in the list of supported extensions

---

install-php-extensions

Install the latest version of gRPC

---

install-php-extensions
scripts/ci-test-extensions

Fix installing gd and vips at the same time

---

.github/workflows/test-dockerfile.yml
Dockerfile

I think you can use a simpler Dockerfile for building your Docker images.

Simplify Dockerfile

---

install-php-extensions

See https://github.com/php/php-src/pull/15230#pullrequestreview-2245823685

pdo_firebird: install Firebird 5 instead of 2.5 on Alpine with PHP 8.4

---

install-php-extensions

This should address issues like https://github.com/mlocati/docker-php-extension-installer/issues/896#issuecomment-2416257165

Upgrade libaom to v3.10.0

---

install-php-extensions

See https://docs.blackfire.io/php/integrations/php-docker#enabling-the-php-probe
Fix #1003

Fix installing blackfire with thread-safe PHP

---

install-php-extensions

Add support for swoole 6

---

.github/workflows/monitor-php8.4.yml
.github/workflows/test-extensions.yml
.github/workflows/test-recent-extensions.yml

Official PHP images now have an Alpine 3.21 variant, test it.

Test Alpine 3.21

---

data/special-requirements

Add support for ionCube Loader on Alpine with PHP 8.4

---

install-php-extensions

Ignore expired apt keys in Debian Stretch

---

install-php-extensions

Fix installing excimer on Alpine <= 3.13

---

.github/workflows/monitor-php8.4.yml
.github/workflows/test-extensions.yml
.github/workflows/test-recent-extensions.yml
data/special-requirements
install-php-extensions

Add support for Debian Trixie
