mlocati/docker-php-extension-installer

- install-php-extensions
libressl is a dependency of rabbitmq-c, and openssl conflicts with libressl
> Use libressl instead of openssl on Alpine

- install-php-extensions
> Fix SSL/snappy dependencies on Debian

- install-php-extensions
Fixed `Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/memcached.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20160303/memcached.so: php_msgpack_serialize: symbol not found in Unknown on line 0`
> Add compatibility memcached with msgpack

- README.md
- Add a caveat on cached image pitfall in the `COPY` section of the `README`
Following up to the point discussed in https://github.com/mlocati/docker-php-extension-installer/issues/242#issuecomment-756007021
> [documentation] Add caveat on COPY cached image

- install-php-extensions
Thanks to https://github.com/FriendsOfPHP/pickle/pull/201 pickle is now able parse versions more correctly.
Closes #248
> Fix installing igbinary with PHP 8

- install-php-extensions
Thanks to https://github.com/eduardok/libsmbclient-php/issues/79 it's now possible again even on old Alpine versions.
> Use recent smbclient version even on old Alpine versions

- install-php-extensions
The new pickle version doesn't require the ZIP php extension anymore.
In addition, it can handle versions much better.
> Updates after new pickle version

- install-php-extensions
I'd like to propose a minor optimization for installing packages by using --no-install-recommends for apt. 
```
--no-install-recommends
Do not consider recommended packages as a dependency for
installing. Configuration Item: APT::Install-Recommends.
```
Pros:
- faster download;
- less image size;
Cons:
- someone can rely on some of recommended and thus installed packages but this is going to be a really rare case and also it's easily fixed with adding a separate `apt-get install` instruction;
As an example: a diff of my own installation log after I added --no-install-recommends:
```patch
-bzip2-doc
cmake
cmake-data
icu-devtools
libarchive13
libbz2-dev
libevent-2.1-6
libfreetype6-dev
libgmp-dev
libgmpxx4ldbl
libgnutls-dane0
libgnutls-openssl27
libgnutls28-dev
libgnutlsxx28
libicu-dev …
```
> Request: add --no-install-recommends

- install-php-extensions
I'm not really sure why, but libgomp has become a required shared library for Imagick.
> Add libgomp as required package for imagemagick@alpine (Fixes #350)

- install-php-extensions
From the `apt-get` manpage:
>  If no package matches the given expression and the expression contains one of '.', '?'
> or '*' then it is assumed to be a POSIX regular expression, and it is applied to all
> package names in the database. Any matches are then installed (or removed). Note that
> matching is done by substring so 'lo.*' matches 'how-lo' and 'lowest'. If this is
> undesired, anchor the regular expression with a '^' or '$' character, or create a more
> specific regular expression.
> Fix apt package regexes on Debian

- install-php-extensions
The regular "linux" build for blackfire extension is incompatible with alpine linux. Attempting to start a profile will cause a segfault in the php(-fpm) process.
But blackfire comes with dedicated builds for alpine linux, so we should use these.
Also, I suppose a test that catches this issue would be helpful. But it requires to actually trigger a profile request in order to cause the segfault, which sounds complicated to do.
> Install the correct version of blackfire on alpine

- README.md
This `sync` call seems unnecessary.
> Remove sync call from README example

- data/special-requirements
Building tensor requires both lapack-dev and openblas-dev
But Alpine maintainers made them incompatible
See https://gitlab.alpinelinux.org/alpine/aports/-/issues/10739
> Tensor is not supported on Alpine 3.15

- install-php-extensions
This used to be installed implicitly within debian-based docker containers by curl, but as of debian 11 isn't.
This is needed to let secure LDAP work out of the box.
Fixes #474
> Add libldap-common to debian dependencies

- install-php-extensions
match bundled install https://github.com/docker-library/php/issues/1268
👍 for stripping, it saves about 20 MB per our CI image build
> Strip symbols only for non-debug PHP build

- install-php-extensions
The MAKE environment variable seems to be only supported on pecl, not with pickle
Use the MAKEFLAGS environment variable which is automatically passed to the child process and is directly supported by make
> Fix parallel compilation with pickle

- install-php-extensions
When trying to install extension from archive on PHP older then 7.2 it throws:
`Fatal error: Uncaught Error: Call to undefined method DOMNodeList::count() in Command line code:16`
DOMNodeList::count was introduced in PHP 7.2
This PR is using length property instead for compatibility with PHP older then 7.2
> using length instead of count for php < 7.2 compatibility

- install-php-extensions
Hey 👋
We're moving from S3 to R2 in the next couple of months. The old S3 links will keep working, but all new version will be published to R2.
> Use R2 URL for ext-relay

- install-php-extensions
As described in #615 we should also ease the use of proxies regardless of the underlying implementation.
This does respect `$http_proxy` or `$HTTP_PROXY` just like pickle / composer did.
> automatically set proxy for pear/pecl

- install-php-extensions
Hi :wave:,
This commit follows #633 ; protobuf and grpc are both impacted
> grpc/protobuf: manually force the latest version

- install-php-extensions
Why we previously forced versions?
See https://github.com/mlocati/docker-php-extension-installer/pull/723
Why we don't need that anymore?
See https://github.com/php/web-pecl/pull/92
> Don't force the latest version of grpc and protobuf

- README.md
- install-php-extensions
This helps in situations when `nproc` or other automatic ways gives wrong number of available CPU count.
> feat: add support for predefined processor count

- install-php-extensions
Prevents msodbcsql17 being installed
> Only install msodbcsql18 on debian 12 Bookworm

- install-php-extensions
VideoLAN's website sometimes comes down at the most inopportune of times and stays down for an unspecified duration. To prevent this from causing errors in build pipelines, I propose we shift it to a much more reliable mirror. Since we don't really rely on latest, this should be fine even if updates on it may lag.
> Use GitHub mirror instead of VideoLAN's for reliability.

- README.md
Hello fellow devs. Just a small contribution.
The ADD statement in Dockerfiles now supports both chown and chmod flags.
This makes images less polluted and less repetitive. DRY to the win. :)
As this was merged a long time ago in Moby, backwards compatibility isn't likely to be an issue.
https://github.com/moby/moby/pull/34263
Docs:
https://docs.docker.com/engine/reference/builder/#add
> Docs: Dockerfile: Updated the ADD statement

- install-php-extensions
Requires https://github.com/php/pecl-database-pdo_oci/issues/2
Close #892
> Add support for oci8 and pdo_oci extensions no longer bundled with PHP

- install-php-extensions
SourceGuardian loader 15 now relies on `libudev`.
<details>
<summary>Error message</summary>
```text
Downloading SourceGuardian... done (version: 15.0.0)
Removing symbols from /usr/local/lib/php/extensions/no-debug-zts-20220829/sourceguardian.so... done (16776 bytes saved).
Check if the sourceguardian module can be loaded... Error loading the "sourceguardian" extension:
Warning: Failed loading Zend extension 'sourceguardian.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20220829/sourceguardian.so (Error loading shared library libudev.so.1: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-zts-20220829/sourceguardian.so)), /usr/local/lib/php/extensions/no-debug-zts-20220829/sourceguardian.so.so (Error loading shared library …
```
> Fix SourceGuardian 15 installation on Alpine Linux

- README.md
- data/special-requirements
Hi,
Adjusted my changes based on the feedback in: https://github.com/mlocati/docker-php-extension-installer/pull/957
> Microsoft ODBC 18 supports ARM architecture. It has been tested successfully at our company. The warning is no longer needed.
> Remove sqlsrv warning for ARM

- install-php-extensions
> Fix installing enchant on PHP < 8 and Alpine 3.12+/Debian 11+

- scripts/ci-test-extensions
The Alpine 3.12 version of PHP 8.0 comes with a rather old PHP (8.0.7).
We still have PHP 8.0 on Alpine 3.13, 3.14, 3.15, and 3.16
> Drop support for PHP 8.0 on Alpine 3.12

- README.md
- install-php-extensions
This PR adds a flag to optionally compile Swoole without enabling io_uring support.
(I am not sure if this is the best way to implement this in the script)
Security experts generally believe io_uring to be unsafe. In fact Google ChromeOS and Android have turned it off, plus all Google production servers turn it off. Based on the blog published by Google below it seems like a bunch of vulnerabilities related to io_uring can be exploited to breakout of the container. [Google Security Blog]
Other security reaserchers also hold this opinion: see the [Blackhat Presentation] on io_uring exploits.
Impact on IPE:
Secure defaults on many container runtimes and operating systems limit `io_uring` syscalls to privileged users holding `CAP_SYS_ADMIN`. If Swoole is compiled with io_uring support …
> Add flag to compile Swoole 6.x without io_uring support

- install-php-extensions
At minimum Swoole 6 on Alpine doesn't experience the segmentation fault with the native curl implementation, under default installation criteria.
This is the initial attempt at a change, we will want to ensure the test cases for Swoole curl cover this change sufficiently.
> Enable Swoole curl-native on Alpine

- install-php-extensions
This PR updates the download URL for the `php-geos` extension to use the GitHub mirror instead of the old git.osgeo.org source, which is no longer available.
Fixes #1084  
- Updated the `php-geos` extension download URL  
- Updated the commit hash for a more recent version
> Fix php-geos extension download URL (#1084)

- .github/workflows/test-extensions.yml
- README.md
- install-php-extensions
For example:
- ```sh
install-php-extensions oci8
```
will install the bundled oci8 extension
- ```sh
install-php-extensions php/pecl-database-oci8@7aa106119c671c9132162b9775e154aeae9ef485
```
will install the oci8 extension downloading it from github
PS: I only tested zip (from PECL), oci8 (from github), pdo_oci (from github)
PPS: Close #1112
> Allow installing remote extensions instead of bundled ones
